<?php
declare( strict_types=1 );

namespace Broseph\Admin;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

class ReportsPage {

	private const PAGE_SLUG = 'broseph-reports';

	private \Broseph\Logging\ReportRepository $repository;

	public function __construct( \Broseph\Logging\ReportRepository $repository ) {
		$this->repository = $repository;
	}

	public function render_page(): void {
		if ( ! current_user_can( 'manage_options' ) ) {
			return;
		}

		// phpcs:ignore WordPress.Security.NonceVerification.Recommended
		$report_id = isset( $_GET['report_id'] ) ? (int) $_GET['report_id'] : 0;

		if ( $report_id > 0 ) {
			$this->render_detail( $report_id );
		} else {
			$this->render_list();
		}
	}

	private function render_list(): void {
		$reports = $this->repository->get_latest( 20 );
		?>
		<div class="wrap broseph-wrap">
			<h1 class="broseph-page-title"><?php esc_html_e( 'Reports', 'broseph' ); ?></h1>
			<p class="description"><?php esc_html_e( 'Latest stored reports generated by Open Claw.', 'broseph' ); ?></p>

			<?php if ( empty( $reports ) ) : ?>
				<p><?php esc_html_e( 'No reports stored yet. Run POST /reports/weekly from Open Claw to generate one.', 'broseph' ); ?></p>
			<?php else : ?>
				<table class="widefat striped broseph-logs-table">
					<thead>
						<tr>
							<th><?php esc_html_e( 'ID', 'broseph' ); ?></th>
							<th><?php esc_html_e( 'Type', 'broseph' ); ?></th>
							<th><?php esc_html_e( 'Status', 'broseph' ); ?></th>
							<th><?php esc_html_e( 'Summary', 'broseph' ); ?></th>
							<th><?php esc_html_e( 'Generated (UTC)', 'broseph' ); ?></th>
							<th><?php esc_html_e( 'View', 'broseph' ); ?></th>
						</tr>
					</thead>
					<tbody>
						<?php foreach ( $reports as $row ) : ?>
							<tr>
								<td><?php echo esc_html( (string) $row['id'] ); ?></td>
								<td><?php echo esc_html( $row['report_type'] ?? '—' ); ?></td>
								<td><?php echo $this->status_badge( (string) ( $row['status'] ?? '' ) ); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped ?></td>
								<td><?php echo esc_html( $row['summary'] ?? '—' ); ?></td>
								<td class="broseph-td-date"><?php echo esc_html( $row['created_at'] ?? '—' ); ?></td>
								<td>
									<a href="<?php echo esc_url( add_query_arg( array( 'page' => self::PAGE_SLUG, 'report_id' => (int) $row['id'] ), admin_url( 'admin.php' ) ) ); ?>">
										<?php esc_html_e( 'View', 'broseph' ); ?>
									</a>
								</td>
							</tr>
						<?php endforeach; ?>
					</tbody>
				</table>
			<?php endif; ?>
		</div>
		<?php
	}

	private function render_detail( int $report_id ): void {
		$report   = $this->repository->get_by_id( $report_id );
		$back_url = add_query_arg( array( 'page' => self::PAGE_SLUG ), admin_url( 'admin.php' ) );
		?>
		<div class="wrap broseph-wrap">
			<h1 class="broseph-page-title">
				<?php esc_html_e( 'Report', 'broseph' ); ?> #<?php echo esc_html( (string) $report_id ); ?>
				<a href="<?php echo esc_url( $back_url ); ?>" class="page-title-action"><?php esc_html_e( '← Back', 'broseph' ); ?></a>
			</h1>

			<?php if ( null === $report ) : ?>
				<p><?php esc_html_e( 'Report not found.', 'broseph' ); ?></p>
			<?php else : ?>
				<p>
					<strong><?php esc_html_e( 'Status:', 'broseph' ); ?></strong>
					<?php echo $this->status_badge( (string) ( $report['status'] ?? '' ) ); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped ?>
					&nbsp;
					<strong><?php esc_html_e( 'Generated:', 'broseph' ); ?></strong>
					<?php echo esc_html( $report['created_at'] ?? '—' ); ?>
				</p>
				<p><?php echo esc_html( $report['summary'] ?? '' ); ?></p>
				<h2><?php esc_html_e( 'Full Report JSON', 'broseph' ); ?></h2>
				<pre style="background:#f6f7f7;padding:1em;overflow:auto;max-height:600px;font-size:12px;"><?php
					$json = json_decode( (string) ( $report['report_json'] ?? '' ), true );
					echo esc_html( wp_json_encode( $json, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES ) );
				?></pre>
			<?php endif; ?>
		</div>
		<?php
	}

	private function status_badge( string $status ): string {
		$lower = strtolower( $status );
		if ( 'healthy' === $lower || str_contains( $lower, 'ok' ) ) {
			$class = 'broseph-badge-success';
		} elseif ( 'critical' === $lower || str_contains( $lower, 'error' ) ) {
			$class = 'broseph-badge-error';
		} elseif ( 'needs_review' === $lower || str_contains( $lower, 'warning' ) ) {
			$class = 'broseph-badge-pending';
		} else {
			$class = 'broseph-badge-default';
		}
		return sprintf(
			'<span class="broseph-badge %s">%s</span>',
			esc_attr( $class ),
			esc_html( $status )
		);
	}
}
