<?php
declare( strict_types=1 );

namespace Broseph\REST;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

class ToolsController extends BaseController {

	private \Broseph\Services\GitPressIntegration $gitpress;
	private \Broseph\Services\DiviService $divi;
	private \Broseph\Services\PermissionsService $permissions;

	public function __construct(
		\Broseph\Auth\RequestSigner $signer,
		\Broseph\Logging\ActionLogger $logger,
		\Broseph\Services\GitPressIntegration $gitpress,
		\Broseph\Services\DiviService $divi,
		\Broseph\Services\PermissionsService $permissions
	) {
		parent::__construct( $signer, $logger );
		$this->gitpress   = $gitpress;
		$this->divi       = $divi;
		$this->permissions = $permissions;
	}

	public function register_routes( string $namespace ): void {
		register_rest_route(
			$namespace,
			'/tools',
			array(
				'methods'             => \WP_REST_Server::READABLE,
				'callback'            => array( $this, 'handle_tools' ),
				'permission_callback' => array( $this, 'require_signed' ),
			)
		);
	}

	public function handle_tools( \WP_REST_Request $request ): \WP_REST_Response {
		$this->logger->log(
			'accepted',
			array(
				'task_type' => 'get_tools',
				'endpoint'  => $request->get_route(),
				'method'    => $request->get_method(),
			)
		);

		$gp_available = $this->gitpress->is_active() && $this->gitpress->is_shortcode_registered();
		$divi_active  = $this->divi->is_divi_active();
		$perms        = $this->permissions->get_permissions_summary();

		return new \WP_REST_Response(
			array(
				'namespace' => 'broseph/v1',
				'base_url'  => rest_url( 'broseph/v1' ),
				'context'   => array(
					'gitpress_available' => $gp_available,
					'divi_active'        => $divi_active,
					'permissions'        => $perms,
				),
				'tools'     => $this->build_manifest( $gp_available, $divi_active, $perms ),
			),
			200
		);
	}

	private function build_manifest( bool $gp, bool $divi, array $perms = array() ): array {
		// Extract permission flags with safe defaults so callers don't need to check keys.
		$p = array_merge(
			array_fill_keys( array_keys( $this->permissions->get_permissions_summary() ), false ),
			$perms
		);
		return array(
			array(
				'name'              => 'get_status',
				'description'       => 'Check plugin health and verify authentication.',
				'method'            => 'GET',
				'endpoint'          => '/broseph/v1/status',
				'risk_level'        => 'read_only',
				'requires_approval' => false,
				'requires_gitpress' => false,
				'requires_divi'     => false,
				'available'         => true,
				'input_schema'      => array(),
				'output_schema'     => array( 'site_url', 'wp_version', 'php_version', 'plugin_version', 'site_id', 'auth_status' ),
			),
			array(
				'name'              => 'run_scan',
				'description'       => 'Full site scan: plugins, themes, form/mail plugins, GitPress status, update availability.',
				'method'            => 'POST',
				'endpoint'          => '/broseph/v1/scan',
				'risk_level'        => 'read_only',
				'requires_approval' => false,
				'requires_gitpress' => false,
				'requires_divi'     => false,
				'available'         => true,
				'input_schema'      => array(),
				'output_schema'     => array( 'active_plugins', 'is_divi_active', 'is_gitpress_active', 'available_plugin_updates' ),
			),
			array(
				'name'              => 'list_pages',
				'description'       => 'List WordPress pages with Divi/GitPress detection flags.',
				'method'            => 'GET',
				'endpoint'          => '/broseph/v1/pages',
				'risk_level'        => 'read_only',
				'requires_approval' => false,
				'requires_gitpress' => false,
				'requires_divi'     => false,
				'available'         => true,
				'input_schema'      => array( 'status', 'search', 'per_page', 'page' ),
				'output_schema'     => array( 'pages', 'total', 'total_pages' ),
			),
			array(
				'name'              => 'get_page',
				'description'       => 'Retrieve a single page including raw content and SEO meta.',
				'method'            => 'GET',
				'endpoint'          => '/broseph/v1/pages/{id}',
				'risk_level'        => 'read_only',
				'requires_approval' => false,
				'requires_gitpress' => false,
				'requires_divi'     => false,
				'available'         => true,
				'input_schema'      => array( 'id' ),
				'output_schema'     => array( 'id', 'title', 'content_raw', 'seo_meta', 'is_divi_page' ),
			),
			array(
				'name'              => 'get_seo_meta',
				'description'       => 'Read SEO metadata for a single page or post, including detected Yoast or Rank Math fields.',
				'method'            => 'GET',
				'endpoint'          => '/broseph/v1/seo/page/{id}',
				'risk_level'        => 'read_only',
				'requires_approval' => false,
				'requires_gitpress' => false,
				'requires_divi'     => false,
				'available'         => true,
				'input_schema'      => array( 'id' ),
				'output_schema'     => array( 'page_id', 'post_type', 'title', 'slug', 'seo_plugin', 'yoast', 'rank_math', 'warnings' ),
			),
			array(
				'name'              => 'update_seo_meta',
				'description'       => 'Update explicit SEO metadata fields only for a single page or post. Supports Yoast now and Rank Math metadata keys when requested.',
				'method'            => 'POST',
				'endpoint'          => '/broseph/v1/seo/page/{id}',
				'risk_level'        => 'metadata_mutation',
				'requires_approval' => false,
				'requires_gitpress' => false,
				'requires_divi'     => false,
				'available'         => $p['can_edit_seo_meta'],
				'input_schema'      => array( 'id', 'seo_plugin', 'title', 'description', 'focus_keyphrase', 'slug' ),
				'output_schema'     => array( 'status', 'page_id', 'seo_plugin', 'updated', 'before', 'after', 'warnings' ),
			),
			array(
				'name'              => 'bulk_update_seo_meta',
				'description'       => 'Bulk update SEO metadata for up to 25 pages or posts in one signed request.',
				'method'            => 'POST',
				'endpoint'          => '/broseph/v1/seo/bulk-update',
				'risk_level'        => 'metadata_mutation',
				'requires_approval' => true,
				'requires_gitpress' => false,
				'requires_divi'     => false,
				'available'         => $p['can_edit_seo_meta'],
				'input_schema'      => array( 'items' ),
				'output_schema'     => array( 'status', 'results' ),
			),
			array(
				'name'              => 'duplicate_page',
				'description'       => 'Duplicate a page as a draft, optionally copying SEO meta.',
				'method'            => 'POST',
				'endpoint'          => '/broseph/v1/pages/duplicate',
				'risk_level'        => 'draft_mutation',
				'requires_approval' => false,
				'requires_gitpress' => false,
				'requires_divi'     => false,
				'available'         => true,
				'input_schema'      => array( 'source_page_id', 'new_title', 'new_slug', 'copy_meta' ),
				'output_schema'     => array( 'new_page_id', 'preview_url', 'edit_url' ),
			),
			array(
				'name'              => 'publish_page',
				'description'       => 'Publish one explicitly selected draft or pending page by ID. Never publishes automatically or in bulk unless IDs are provided.',
				'method'            => 'POST',
				'endpoint'          => '/broseph/v1/pages/{id}/publish',
				'risk_level'        => 'publish_mutation',
				'requires_approval' => true,
				'requires_gitpress' => false,
				'requires_divi'     => false,
				'available'         => $p['can_publish_pages'],
				'input_schema'      => array( 'id', 'expected_current_status' ),
				'output_schema'     => array( 'status', 'page_id', 'previous_status', 'new_status', 'permalink', 'warnings' ),
			),
			array(
				'name'              => 'bulk_publish_pages',
				'description'       => 'Publish up to 25 explicitly listed draft or pending pages by ID. Never publishes anything not listed.',
				'method'            => 'POST',
				'endpoint'          => '/broseph/v1/pages/bulk-publish',
				'risk_level'        => 'publish_mutation',
				'requires_approval' => true,
				'requires_gitpress' => false,
				'requires_divi'     => false,
				'available'         => $p['can_publish_pages'],
				'input_schema'      => array( 'page_ids' ),
				'output_schema'     => array( 'summary', 'results', 'warnings' ),
			),
			array(
				'name'              => 'trash_draft_page',
				'description'       => 'Trash one explicitly selected draft or pending page by ID. Never permanently deletes and never trashes published pages.',
				'method'            => 'POST',
				'endpoint'          => '/broseph/v1/pages/{id}/trash',
				'risk_level'        => 'trash_mutation',
				'requires_approval' => true,
				'requires_gitpress' => false,
				'requires_divi'     => false,
				'available'         => $p['can_delete_drafts'],
				'input_schema'      => array( 'id' ),
				'output_schema'     => array( 'status', 'page_id', 'previous_status', 'new_status' ),
			),
			array(
				'name'              => 'bulk_trash_drafts',
				'description'       => 'Trash up to 25 explicitly listed draft or pending pages by ID. Never permanently deletes and never trashes published pages.',
				'method'            => 'POST',
				'endpoint'          => '/broseph/v1/pages/bulk-trash',
				'risk_level'        => 'trash_mutation',
				'requires_approval' => true,
				'requires_gitpress' => false,
				'requires_divi'     => false,
				'available'         => $p['can_delete_drafts'],
				'input_schema'      => array( 'page_ids' ),
				'output_schema'     => array( 'summary', 'results', 'warnings' ),
			),
			array(
				'name'              => 'create_landing_page',
				'description'       => 'Legacy combined landing page creator (native/GitPress template modes). For new AI-generated pages, prefer create_gitpress_page or create_divi_page_from_template instead.',
				'method'            => 'POST',
				'endpoint'          => '/broseph/v1/landing-pages/create',
				'risk_level'        => 'draft_mutation',
				'requires_approval' => false,
				'requires_gitpress' => false,
				'requires_divi'     => false,
				'available'         => true,
				'input_schema'      => array( 'mode', 'template_page_id', 'title', 'slug', 'excerpt', 'replacements', 'meta', 'gitpress' ),
				'output_schema'     => array( 'status', 'strategy', 'page_id', 'preview_url', 'replaced_tokens', 'required_github_files', 'warnings' ),
			),
			array(
				'name'              => 'resolve_content_strategy',
				'description'       => 'Ask Broseph which page creation strategy to use. Returns the recommended strategy, the exact endpoint to call next, and what dependencies are required. Call this before creating any page if you are unsure which workflow to use.',
				'method'            => 'POST',
				'endpoint'          => '/broseph/v1/content/resolve-strategy',
				'risk_level'        => 'read_only',
				'requires_approval' => false,
				'requires_gitpress' => false,
				'requires_divi'     => false,
				'available'         => true,
				'input_schema'      => array( 'task_type', 'preferred_mode', 'page_id', 'template_page_id', 'risk_tolerance', 'requires_gitpress', 'requires_divi_layout' ),
				'output_schema'     => array( 'strategy', 'endpoint', 'reason', 'requires_github_files', 'requires_divi', 'requires_gitpress', 'requires_existing_page', 'requires_template_page', 'requires_approval', 'warnings' ),
			),
			array(
				'name'              => 'get_gitpress_status',
				'description'       => 'Check whether GitPress is active and the shortcode is registered.',
				'method'            => 'GET',
				'endpoint'          => '/broseph/v1/gitpress/status',
				'risk_level'        => 'read_only',
				'requires_approval' => false,
				'requires_gitpress' => true,
				'requires_divi'     => false,
				'available'         => $gp,
				'input_schema'      => array(),
				'output_schema'     => array( 'is_active', 'shortcode_registered', 'shortcode_name', 'plugin_detected_name' ),
			),
			array(
				'name'              => 'scan_gitpress_usages',
				'description'       => 'Scan all pages for [divi_github_content] shortcode usages.',
				'method'            => 'GET',
				'endpoint'          => '/broseph/v1/gitpress/usages',
				'risk_level'        => 'read_only',
				'requires_approval' => false,
				'requires_gitpress' => true,
				'requires_divi'     => false,
				'available'         => true,
				'input_schema'      => array(),
				'output_schema'     => array( 'usages', 'count' ),
			),
			array(
				'name'              => 'validate_gitpress_shortcode',
				'description'       => 'Validate a [divi_github_content] shortcode before using it.',
				'method'            => 'POST',
				'endpoint'          => '/broseph/v1/gitpress/validate-shortcode',
				'risk_level'        => 'read_only',
				'requires_approval' => false,
				'requires_gitpress' => true,
				'requires_divi'     => false,
				'available'         => true,
				'input_schema'      => array( 'shortcode' ),
				'output_schema'     => array( 'valid', 'errors' ),
			),
			array(
				'name'              => 'create_gitpress_page',
				'description'       => 'Default for new AI-generated landing pages. Creates a draft page using GitPress page-level shortcode/full-page canvas. Does not use Divi Builder. Requires the "Allow GitPress page creation" permission setting.',
				'method'            => 'POST',
				'endpoint'          => '/broseph/v1/gitpress/pages/create',
				'risk_level'        => 'draft_mutation',
				'requires_approval' => false,
				'requires_gitpress' => true,
				'requires_divi'     => false,
				'available'         => $gp && $p['can_create_gitpress_pages'],
				'input_schema'      => array( 'title', 'slug', 'excerpt', 'shortcode', 'render_position', 'full_page_canvas', 'meta' ),
				'output_schema'     => array( 'status', 'page_id', 'preview_url', 'edit_url', 'shortcode', 'render_position', 'full_page_canvas', 'warnings' ),
			),
			array(
				'name'              => 'get_gitpress_page_settings',
				'description'       => 'Read the GitPress page-level shortcode/metabox settings for a given page.',
				'method'            => 'GET',
				'endpoint'          => '/broseph/v1/gitpress/pages/{id}',
				'risk_level'        => 'read_only',
				'requires_approval' => false,
				'requires_gitpress' => false,
				'requires_divi'     => false,
				'available'         => true,
				'input_schema'      => array( 'id' ),
				'output_schema'     => array( 'page_id', 'title', 'shortcode', 'render_position', 'full_page_canvas', 'has_gitpress_shortcode', 'preview_url', 'edit_url' ),
			),
			array(
				'name'              => 'get_divi_page_summary',
				'description'       => 'Parse and summarize the Divi module structure of a page.',
				'method'            => 'GET',
				'endpoint'          => '/broseph/v1/divi/page/{id}/summary',
				'risk_level'        => 'read_only',
				'requires_approval' => false,
				'requires_gitpress' => false,
				'requires_divi'     => true,
				'available'         => $divi,
				'input_schema'      => array( 'id' ),
				'output_schema'     => array( 'page_id', 'is_divi_page', 'module_count', 'modules', 'warnings' ),
			),
			array(
				'name'              => 'insert_gitpress_code_module',
				'description'       => 'Use only for adding GitPress content to an existing Divi page. Inserts a [divi_github_content] shortcode as a Divi Code Module. Do not use this for brand-new pages — use create_gitpress_page instead.',
				'method'            => 'POST',
				'endpoint'          => '/broseph/v1/divi/code-module/insert-gitpress',
				'risk_level'        => 'draft_mutation',
				'requires_approval' => false,
				'requires_gitpress' => true,
				'requires_divi'     => true,
				'available'         => $divi && $gp && $p['can_edit_divi_code_modules'],
				'input_schema'      => array( 'page_id', 'shortcode', 'placement', 'save_mode' ),
				'output_schema'     => array( 'target_page_id', 'original_page_id', 'preview_url', 'inserted_shortcode', 'save_mode_used' ),
			),
			array(
				'name'              => 'generate_weekly_report',
				'description'       => 'Run the weekly site health report and store it.',
				'method'            => 'POST',
				'endpoint'          => '/broseph/v1/reports/weekly',
				'risk_level'        => 'read_only',
				'requires_approval' => false,
				'requires_gitpress' => false,
				'requires_divi'     => false,
				'available'         => true,
				'input_schema'      => array(),
				'output_schema'     => array( 'status', 'summary', 'checks', 'recommendations', 'approval_required' ),
			),
			array(
				'name'              => 'list_forms',
				'description'       => 'Discover all contact forms on the site: CF7, WPForms, Gravity Forms, Fluent Forms, Ninja Forms, and Divi Contact Form modules.',
				'method'            => 'GET',
				'endpoint'          => '/broseph/v1/forms',
				'risk_level'        => 'read_only',
				'requires_approval' => false,
				'requires_gitpress' => false,
				'requires_divi'     => false,
				'available'         => true,
				'input_schema'      => array(),
				'output_schema'     => array( 'forms', 'count' ),
			),
			array(
				'name'              => 'get_page_forms',
				'description'       => 'List all contact forms detected on a specific page by ID.',
				'method'            => 'GET',
				'endpoint'          => '/broseph/v1/forms/page/{id}',
				'risk_level'        => 'read_only',
				'requires_approval' => false,
				'requires_gitpress' => false,
				'requires_divi'     => false,
				'available'         => true,
				'input_schema'      => array( 'id' ),
				'output_schema'     => array( 'page_id', 'page_title', 'page_url', 'forms', 'count' ),
			),
			array(
				'name'              => 'test_form',
				'description'       => 'Submit a real controlled payload to a detected Divi contact form via Divi\'s AJAX handler. This MAY send an email to the form\'s configured recipient. Returns submitted/failed/unsupported — never fakes success. Requires "Allow contact form submission tests" permission.',
				'method'            => 'POST',
				'endpoint'          => '/broseph/v1/forms/test',
				'risk_level'        => 'external_effect_mail_send',
				'requires_approval' => true,
				'requires_gitpress' => false,
				'requires_divi'     => true,
				'available'         => $divi && $p['can_submit_form_tests'],
				'input_schema'      => array( 'form_type', 'page_id', 'form_id', 'test_payload' ),
				'output_schema'     => array( 'status', 'test_supported', 'form_type', 'page_id', 'form_title', 'submitted_fields_masked', 'response_message', 'mail_check_hint', 'warnings' ),
			),
			array(
				'name'              => 'full_test_form',
				'description'       => 'Orchestrated form test: submits the form via Divi\'s AJAX handler, then checks recent mail logs for delivery confirmation. Fallback to wp_mail() if allowed. Requires "Allow contact form submission tests" or mail permissions.',
				'method'            => 'POST',
				'endpoint'          => '/broseph/v1/forms/full-test',
				'risk_level'        => 'external_effect_mail_send',
				'requires_approval' => true,
				'requires_gitpress' => false,
				'requires_divi'     => true,
				'available'         => $divi && ( $p['can_submit_form_tests'] || ( $p['can_send_mail_tests'] && $p['can_use_form_mail_fallback'] ) ),
				'input_schema'      => array( 'form_type', 'page_id', 'test_payload', 'fallback_mail_test', 'fallback_to', 'mail_log_window_seconds' ),
				'output_schema'     => array( 'final_result', 'form_type', 'page_id', 'form_title', 'submission_status', 'submission_result', 'delivery_status', 'mail_log_source', 'fallback_used', 'submitted_fields_masked', 'warnings', 'note' ),
			),
			array(
				'name'              => 'send_mail_test',
				'description'       => 'Send a real wp_mail() test through the site\'s configured WP Mail SMTP setup. Returns sent/failed with masked recipient. Requires the "Allow mail tests" permission setting.',
				'method'            => 'POST',
				'endpoint'          => '/broseph/v1/mail/test',
				'risk_level'        => 'mail_send',
				'requires_approval' => false,
				'requires_gitpress' => false,
				'requires_divi'     => false,
				'available'         => $p['can_send_mail_tests'],
				'input_schema'      => array( 'to', 'label', 'include_site_info' ),
				'output_schema'     => array( 'status', 'wp_mail_result', 'recipient_masked', 'recipient_domain', 'subject', 'timestamp', 'notes' ),
			),
			array(
				'name'              => 'get_recent_mail_logs',
				'description'       => 'Retrieve recent mail log entries from WP Mail SMTP, WP Mail Logging, or FluentSMTP. Returns supported: false if no logging plugin is active.',
				'method'            => 'GET',
				'endpoint'          => '/broseph/v1/mail/logs/recent',
				'risk_level'        => 'read_only',
				'requires_approval' => false,
				'requires_gitpress' => false,
				'requires_divi'     => false,
				'available'         => true,
				'input_schema'      => array( 'limit' ),
				'output_schema'     => array( 'supported', 'source_plugin', 'logs', 'message' ),
			),
			array(
				'name'              => 'create_divi_page_from_template',
				'description'       => 'Use when a new page must clone an existing Divi layout/template. Copies Divi content, applies placeholder replacements, preserves Divi Builder activation, and optionally appends Code Modules.',
				'method'            => 'POST',
				'endpoint'          => '/broseph/v1/divi/pages/create-from-template',
				'risk_level'        => 'draft_mutation',
				'requires_approval' => false,
				'requires_gitpress' => false,
				'requires_divi'     => true,
				'available'         => $divi && $p['can_create_divi_template_pages'],
				'input_schema'      => array( 'template_page_id', 'title', 'slug', 'excerpt', 'replacements', 'meta', 'code_modules' ),
				'output_schema'     => array( 'status', 'page_id', 'preview_url', 'edit_url', 'divi_builder_active', 'inserted_code_modules', 'replaced_tokens', 'warnings' ),
			),
			array(
				'name'              => 'check_updates',
				'description'       => 'Read-only check for available plugin and theme updates. Does not apply any updates.',
				'method'            => 'GET',
				'endpoint'          => '/broseph/v1/updates',
				'risk_level'        => 'read_only',
				'requires_approval' => false,
				'requires_gitpress' => false,
				'requires_divi'     => false,
				'available'         => true,
				'input_schema'      => array(),
				'output_schema'     => array( 'plugins', 'themes', 'updates_allowed', 'notes' ),
			),
			array(
				'name'              => 'update_selected_plugins',
				'description'       => 'Update explicitly listed plugins by file path. Requires "Allow plugin updates" in Broseph > Permissions. Only plugins named in plugin_files are updated — no bulk updates. Broseph itself is always skipped.',
				'method'            => 'POST',
				'endpoint'          => '/broseph/v1/updates/plugins/update-selected',
				'risk_level'        => 'risky_mutation',
				'requires_approval' => true,
				'requires_gitpress' => false,
				'requires_divi'     => false,
				'available'         => $p['can_update_plugins'],
				'input_schema'      => array( 'plugin_files', 'allow_inactive' ),
				'output_schema'     => array( 'results', 'summary' ),
			),
			array(
				'name'              => 'update_selected_themes',
				'description'       => 'Update explicitly listed themes by slug. Requires "Allow theme updates" in Broseph > Permissions. Only themes named in the themes array are updated — no bulk updates. The active theme is skipped unless allow_active_theme: true and the active-theme permission is enabled.',
				'method'            => 'POST',
				'endpoint'          => '/broseph/v1/updates/themes/update-selected',
				'risk_level'        => 'risky_mutation',
				'requires_approval' => true,
				'requires_gitpress' => false,
				'requires_divi'     => false,
				'available'         => $p['can_update_themes'],
				'input_schema'      => array( 'themes', 'allow_active_theme' ),
				'output_schema'     => array( 'results', 'summary' ),
			),
		);
	}
}
